// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFnGOpplLQ0aqiX0w8uhUZ-iT3JRKkr8',
    appId: '1:53239872717:web:1b7d8be560428c6b80bd84',
    messagingSenderId: '53239872717',
    projectId: 'study-app-aacff',
    authDomain: 'study-app-aacff.firebaseapp.com',
    storageBucket: 'study-app-aacff.appspot.com',
    measurementId: 'G-70CN8ZVX8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLQ3Co3aZFtDFQA2NhjZ2eEIo8PVnl2U',
    appId: '1:53239872717:android:e6c05cb15f21243780bd84',
    messagingSenderId: '53239872717',
    projectId: 'study-app-aacff',
    storageBucket: 'study-app-aacff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnQwGmTtgV-5p-LniyhW3lO8pAWC2Ovr4',
    appId: '1:53239872717:ios:c6b767b741403e4980bd84',
    messagingSenderId: '53239872717',
    projectId: 'study-app-aacff',
    storageBucket: 'study-app-aacff.appspot.com',
    iosClientId: '53239872717-k8dgfbtqiospuvs9eeukk46ftc0jfc9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnQwGmTtgV-5p-LniyhW3lO8pAWC2Ovr4',
    appId: '1:53239872717:ios:c6b767b741403e4980bd84',
    messagingSenderId: '53239872717',
    projectId: 'study-app-aacff',
    storageBucket: 'study-app-aacff.appspot.com',
    iosClientId: '53239872717-k8dgfbtqiospuvs9eeukk46ftc0jfc9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
